# Prepare a pool of scratch orgs

trigger: none

schedules:
- cron: "0 0 * * *"
  displayName: Daily midnight prepare pool
  branches:
    include:
    - develop
  always: true

pool:
  vmImage: 'ubuntu-latest'

variables:
  group: DEVHUB

steps:
- task: DownloadSecureFile@1
  name: devhubKey
  inputs:
    secureFile: 'DEVHUB_SERVER_KEY'

- script: |
          wget https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
          mkdir sfdx-cli
          tar xJf sfdx-linux-amd64.tar.xz -C sfdx-cli --strip-components 1
          ./sfdx-cli/install
          echo 'y' | sfdx plugins:install sfpowerkit
          echo 'y' | sfdx plugins:install @dxatscale/sfpowerscripts@hotfix
  displayName: 'Install SFDX and Plugins'

- script: |
          sfdx auth:jwt:grant -u $(DEVHUB_USERNAME) -i $(DEVHUB_CLIENT_ID) -f $(devhubKey.secureFilePath) -a devhub -r https://login.salesforce.com
  displayName: 'Authenticate DevHub'


- script: |
           sfdx sfpowerscripts:orchestrator:prepare -t CI2 -v devhub --installall --installassourcepackages -m 2
  displayName: 'Prepare a pool of scratch orgs'
