# Prepare a pool of scratch orgs

trigger: none

schedules:
    - cron: '0 0 * * *'
      displayName: Daily midnight prepare pool
      branches:
          include:
              - develop
      always: true

pool:
    vmImage: 'ubuntu-latest'

container: dxatscale/sfpowerscripts:latest

variables:
  - group: DEVHUB

steps:
    - task: DownloadSecureFile@1
      name: devhubKey
      inputs:
          secureFile: 'DEVHUB_SERVER_KEY'

    - script: |
          sfdx auth:jwt:grant -u $(DEVHUB_USERNAME) -i $(DEVHUB_CLIENT_ID) -f $(devhubKey.secureFilePath) -a devhub -r https://login.salesforce.com
      displayName: 'Authenticate DevHub'

    - script: |
          sfdx sfpowerscripts:orchestrator:prepare -t CI2 -v devhub --installall --installassourcepackages -m 2 --succeedondeploymenterrors
      displayName: 'Prepare a pool of scratch orgs'
