# Unique name for this workflow
name: sfpowerscripts validate

# Definition when the workflow should run
on:
    workflow_dispatch:
    pull_request:
        types: [opened, synchronize, reopened]
        branches:
            - develop

# Jobs to be executed
jobs:
    validate:
        runs-on: ubuntu-latest
        steps:
            # Install sfdx and plugins
            - name: Install SFDX and Plugins
              run: |
                  npm i sfdx-cli -g 
                  echo 'y' | sfdx plugins:install sfpowerkit
                  echo 'y' | sfdx plugins:install @dxatscale/sfpowerscripts
            # Checkout the code in the pull request
            - name: 'Checkout source code'
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0

            # Copy Dev Hub server key to file
            - name: 'Copy Dev Hub server key to file'
              shell: bash
              run: |
                  echo "${SALESFORCE_JWT_SECRET_KEY}" > ./JWT_KEYFILE
              env:
                  SALESFORCE_JWT_SECRET_KEY: ${{ secrets.DEVHUB_SERVER_KEY }}

            # Validate source and trigger test
            - name: 'Push source to scratch org'
              run: 'sfdx sfpowerscripts:orchestrator:validate -f ./JWT_KEYFILE -i ${{ secrets.DEVHUB_CLIENT_ID }} -p CI1 -u  ${{ secrets.DEVHUB_USERNAME }} -x'

            # Upload code coverage data
            - name: 'Upload code coverage for Apex to Codecov.io'
              uses: codecov/codecov-action@v1
              with:
                  flags: Apex
